name: Release

on:
  release:
    types:
      - published

env:
  PYTHON_VERSION: "3.14"
  NODE_OPTIONS: --max_old_space_size=6144

permissions:
  actions: none

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      id-token: write
    if: github.repository_owner == 'yuanzhou029'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Fix script permissions
        run: |
          chmod +x script/release
          chmod +x script/build_frontend
          chmod +x landing-page/script/build_landing_page

      - name: Install dependencies
        run: yarn install

      - name: Build and release package
        run: |
          python3 -m pip install build
          export SKIP_FETCH_NIGHTLY_TRANSLATIONS=1
          script/release

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

  release-landing-page:
    name: Release landing-page frontend
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: yarn

      - name: Fix script permissions
        run: chmod +x landing-page/script/build_landing_page

      - name: Install dependencies
        run: yarn install

      - name: Build landing-page
        run: landing-page/script/build_landing_page

      - name: Tar folder
        run: tar -czf landing-page/home_assistant_frontend_landingpage-${{ github.event.release.tag_name }}.tar.gz -C landing-page/dist .

      - name: Upload release asset
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: landing-page/home_assistant_frontend_landingpage-${{ github.event.release.tag_name }}.tar.gz
